from ovd.datasets.coco_zeroshot import categories_unseen

coco_categories = {
    1: {'supercategory': 'person', 'id': 1, 'name': 'person', 'frequency': 0},
    2: {'supercategory': 'vehicle', 'id': 2, 'name': 'bicycle', 'frequency': 0},
    3: {'supercategory': 'vehicle', 'id': 3, 'name': 'car', 'frequency': 0},
    4: {'supercategory': 'vehicle', 'id': 4, 'name': 'motorcycle', 'frequency': 0},
    5: {'supercategory': 'vehicle', 'id': 5, 'name': 'airplane', 'frequency': 0},
    6: {'supercategory': 'vehicle', 'id': 6, 'name': 'bus', 'frequency': 0},
    7: {'supercategory': 'vehicle', 'id': 7, 'name': 'train', 'frequency': 0},
    8: {'supercategory': 'vehicle', 'id': 8, 'name': 'truck', 'frequency': 0},
    9: {'supercategory': 'vehicle', 'id': 9, 'name': 'boat', 'frequency': 0},
    10: {'supercategory': 'outdoor', 'id': 10, 'name': 'traffic light', 'frequency': 0},
    11: {'supercategory': 'outdoor', 'id': 11, 'name': 'fire hydrant', 'frequency': 0},
    13: {'supercategory': 'outdoor', 'id': 13, 'name': 'stop sign', 'frequency': 0},
    14: {'supercategory': 'outdoor', 'id': 14, 'name': 'parking meter', 'frequency': 0},
    15: {'supercategory': 'outdoor', 'id': 15, 'name': 'bench', 'frequency': 0},
    16: {'supercategory': 'animal', 'id': 16, 'name': 'bird', 'frequency': 0},
    17: {'supercategory': 'animal', 'id': 17, 'name': 'cat', 'frequency': 0},
    18: {'supercategory': 'animal', 'id': 18, 'name': 'dog', 'frequency': 0},
    19: {'supercategory': 'animal', 'id': 19, 'name': 'horse', 'frequency': 0},
    20: {'supercategory': 'animal', 'id': 20, 'name': 'sheep', 'frequency': 0},
    21: {'supercategory': 'animal', 'id': 21, 'name': 'cow', 'frequency': 0},
    22: {'supercategory': 'animal', 'id': 22, 'name': 'elephant', 'frequency': 0},
    23: {'supercategory': 'animal', 'id': 23, 'name': 'bear', 'frequency': 0},
    24: {'supercategory': 'animal', 'id': 24, 'name': 'zebra', 'frequency': 0},
    25: {'supercategory': 'animal', 'id': 25, 'name': 'giraffe', 'frequency': 0},
    27: {'supercategory': 'accessory', 'id': 27, 'name': 'backpack', 'frequency': 0},
    28: {'supercategory': 'accessory', 'id': 28, 'name': 'umbrella', 'frequency': 0},
    31: {'supercategory': 'accessory', 'id': 31, 'name': 'handbag', 'frequency': 0},
    32: {'supercategory': 'accessory', 'id': 32, 'name': 'tie', 'frequency': 0},
    33: {'supercategory': 'accessory', 'id': 33, 'name': 'suitcase', 'frequency': 0},
    34: {'supercategory': 'sports', 'id': 34, 'name': 'frisbee', 'frequency': 0},
    35: {'supercategory': 'sports', 'id': 35, 'name': 'skis', 'frequency': 0},
    36: {'supercategory': 'sports', 'id': 36, 'name': 'snowboard', 'frequency': 0},
    37: {'supercategory': 'sports', 'id': 37, 'name': 'sports ball', 'frequency': 0},
    38: {'supercategory': 'sports', 'id': 38, 'name': 'kite', 'frequency': 0},
    39: {'supercategory': 'sports', 'id': 39, 'name': 'baseball bat', 'frequency': 0},
    40: {'supercategory': 'sports', 'id': 40, 'name': 'baseball glove', 'frequency': 0},
    41: {'supercategory': 'sports', 'id': 41, 'name': 'skateboard', 'frequency': 0},
    42: {'supercategory': 'sports', 'id': 42, 'name': 'surfboard', 'frequency': 0},
    43: {'supercategory': 'sports', 'id': 43, 'name': 'tennis racket', 'frequency': 0},
    44: {'supercategory': 'kitchen', 'id': 44, 'name': 'bottle', 'frequency': 0},
    46: {'supercategory': 'kitchen', 'id': 46, 'name': 'wine glass', 'frequency': 0},
    47: {'supercategory': 'kitchen', 'id': 47, 'name': 'cup', 'frequency': 0},
    48: {'supercategory': 'kitchen', 'id': 48, 'name': 'fork', 'frequency': 0},
    49: {'supercategory': 'kitchen', 'id': 49, 'name': 'knife', 'frequency': 0},
    50: {'supercategory': 'kitchen', 'id': 50, 'name': 'spoon', 'frequency': 0},
    51: {'supercategory': 'kitchen', 'id': 51, 'name': 'bowl', 'frequency': 0},
    52: {'supercategory': 'food', 'id': 52, 'name': 'banana', 'frequency': 0},
    53: {'supercategory': 'food', 'id': 53, 'name': 'apple', 'frequency': 0},
    54: {'supercategory': 'food', 'id': 54, 'name': 'sandwich', 'frequency': 0},
    55: {'supercategory': 'food', 'id': 55, 'name': 'orange', 'frequency': 0},
    56: {'supercategory': 'food', 'id': 56, 'name': 'broccoli', 'frequency': 0},
    57: {'supercategory': 'food', 'id': 57, 'name': 'carrot', 'frequency': 0},
    58: {'supercategory': 'food', 'id': 58, 'name': 'hot dog', 'frequency': 0},
    59: {'supercategory': 'food', 'id': 59, 'name': 'pizza', 'frequency': 0},
    60: {'supercategory': 'food', 'id': 60, 'name': 'donut', 'frequency': 0},
    61: {'supercategory': 'food', 'id': 61, 'name': 'cake', 'frequency': 0},
    62: {'supercategory': 'furniture', 'id': 62, 'name': 'chair', 'frequency': 0},
    63: {'supercategory': 'furniture', 'id': 63, 'name': 'couch', 'frequency': 0},
    64: {'supercategory': 'furniture', 'id': 64, 'name': 'potted plant', 'frequency': 0},
    65: {'supercategory': 'furniture', 'id': 65, 'name': 'bed', 'frequency': 0},
    67: {'supercategory': 'furniture', 'id': 67, 'name': 'dining table', 'frequency': 0},
    70: {'supercategory': 'furniture', 'id': 70, 'name': 'toilet', 'frequency': 0},
    72: {'supercategory': 'electronic', 'id': 72, 'name': 'tv', 'frequency': 0},
    73: {'supercategory': 'electronic', 'id': 73, 'name': 'laptop', 'frequency': 0},
    74: {'supercategory': 'electronic', 'id': 74, 'name': 'mouse', 'frequency': 0},
    75: {'supercategory': 'electronic', 'id': 75, 'name': 'remote', 'frequency': 0},
    76: {'supercategory': 'electronic', 'id': 76, 'name': 'keyboard', 'frequency': 0},
    77: {'supercategory': 'electronic', 'id': 77, 'name': 'cell phone', 'frequency': 0},
    78: {'supercategory': 'appliance', 'id': 78, 'name': 'microwave', 'frequency': 0},
    79: {'supercategory': 'appliance', 'id': 79, 'name': 'oven', 'frequency': 0},
    80: {'supercategory': 'appliance', 'id': 80, 'name': 'toaster', 'frequency': 0},
    81: {'supercategory': 'appliance', 'id': 81, 'name': 'sink', 'frequency': 0},
    82: {'supercategory': 'appliance', 'id': 82, 'name': 'refrigerator', 'frequency': 0},
    84: {'supercategory': 'indoor', 'id': 84, 'name': 'book', 'frequency': 0},
    85: {'supercategory': 'indoor', 'id': 85, 'name': 'clock', 'frequency': 0},
    86: {'supercategory': 'indoor', 'id': 86, 'name': 'vase', 'frequency': 0},
    87: {'supercategory': 'indoor', 'id': 87, 'name': 'scissors', 'frequency': 0},
    88: {'supercategory': 'indoor', 'id': 88, 'name': 'teddy bear', 'frequency': 0},
    89: {'supercategory': 'indoor', 'id': 89, 'name': 'hair drier', 'frequency': 0},
    90: {'supercategory': 'indoor', 'id': 90, 'name': 'toothbrush', 'frequency': 0}}


def get_query(cat_id):
    category = coco_categories[cat_id]["name"]
    query = f"every {category}"
    unseen = True if cat_id in categories_unseen.keys() else False

    return query, unseen
